name: bitcoin_bip44
version: 0.1.5
description: Library implementing Bitcoins BIP44 (HD wallet organization)
  specification in a Flutter friendly fashion.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  base58check: ^2.0.0
  bech32: ^0.2.1
  bitcoin_bip32:
    git: https://github.com/crackerli/bitcoin_bip32
  http: ^0.13.0
  pointycastle: ^3.0.1

dev_dependencies:
  hex: ^0.2.0
  mock_web_server: ^4.1.1
  pedantic: ^1.9.0
  test: ^1.14.2

environment:
  sdk: ">=2.13.4 <3.0.0"
